{% set version = '1.1' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-loe
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/loe_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/loe/loe_{{ version }}.tar.gz
  sha256: cc100c98bee78f6d11bc6227c8585bdc8bb7d55e4bf69ec4b16ca7d7ddbb26d8

build:
  merge_build_host: True  # [win]
  number: 1004
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}              # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-mass
  run:
    - r-base
    - {{ native }}gcc-libs         # [win]
    - r-mass

test:
  commands:
    - $R -e "library('loe')"  # [not win]
    - "\"%R%\" -e \"library('loe')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=loe
  license: GPL-2.0-or-later
  summary: Local Ordinal embedding (LOE) is one of graph embedding methods for unweighted graphs.
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
