{% set version = '1.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-loe
  version: {{ version|replace("-", "_") }}

source:
  fn: loe_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/loe_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/loe/loe_{{ version }}.tar.gz
  sha256: cc100c98bee78f6d11bc6227c8585bdc8bb7d55e4bf69ec4b16ca7d7ddbb26d8

build:
  merge_build_host: True  # [win]
  number: 1001
  rpaths:
    - lib/R/lib/
    - lib/
  skip: true  # [win32]

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base
    - r-mass

  run:
    - r-base
    - r-mass

test:
  commands:
    - $R -e "library('loe')"  # [not win]
    - "\"%R%\" -e \"library('loe')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=loe
  license: GPL (>= 2)
  summary: Local Ordinal embedding (LOE) is one of graph embedding methods for unweighted graphs.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
