appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: K8TLnmf84gaAaisl2jrEhDCtJjVffNg/Fmkt8UAgSAayrYRC0CRj+dATACxP1sYrm0OM6Gn06sNN7m7jrglLGGC293u1OKgqnDG5Bs++nAVVm/LeDYb11FFWx23tMkWMWalxpmJ7hYWxYpIejG9MdVpIsgztf3+HMz8KjHaunAQQcibB9tNGLKSE6etOzGcjjVeg5h64+A42Bc6ZdAXuh/fo/B0Mx+V+TArzcEoVWW1V9rSPhC8jYJOubFllo+piKaCT+X1k+K16Ue+DC1JR489R3Lor100HZ/Oz3+tk7vqBPYzQrz0EzLhlt9JLGyHrL+jTtupJ0obGpve3788eCYX/VhTbkwxrjnoDoMF6FdRig0aJGNcabRxIEMojvxJqH13C24aiZUHBWRzvFk8XPiHW2FPTaI6aaNdmSRLt+bhpmC58LHzenAldQwxOT86K9QNDYqYyKR4DFGcKvJDlegKw841HV7iFb8PDQ1et8A0EpPKqfXOEQuZKbpHsWCf8TWctCjxCH5qKBcFuWcQpAWlsniSNYZHPefetEmOvcZbqUvtAy9YdBRutI79ccGgdPTq25ZVo3K9eJxtNntQNwsZzSGgqQUauliJp/Wpp3KYl8YYabU3Q9QlE8I3t8L6rElFTKsY5Sgz8eVcniLRLRP9yA0Tr4KU7hW49YxUPlS8=}
bot:
  automerge: true
