travis:
  secure:
    BINSTAR_TOKEN: AtjjyLdcJT1vc4z7Jy7i7hMM5+Xh60tcNEfO75HrPvLVm+TuB2wjWQopZELxzZ+R4L+fEYDkq6Gn9+rvoXXk/hsq61NiE0ayoqekmzevV5iomNKkDJnSSMmenbFqJsTIvgzpiBeuSeMa4I/AuD5qg7tdcV2Ibb3YQxC0a6uSAjjcwWntABBw2UBlNSe+Y7Isw0kaHPaDiBvngX3CAVgVQGXx1GO7Oru4BIZedfL5mIb7l8kXMuk8TcMjFQVODJddI4VI3E3wSKvFATfN8Bn/6FS90OdvtnEdetyDm7pVY6Hry8ULevrV4MYpaVWZhmsXR6Fj2b/AIVCCQEJZBFpD+t9/JYdL0ni1oHS7Nk22bTzFpz1cz3UW4uQR3r9WfLeZvNbj7nshs2jiwfDwBPyQr4a5BUrNLRIeMv4oL9VJiGHxPiHEsXl1eQr/j8P6oT00HJJVxecyAr3pC9C/Qbkodu4YW1GbYeZ4h3mPyLnt+qovsvP2696sG1j2+XfiiNjlBxWTQBMx9gvuZT+E8HOJVJupSi8cEe4hypGXn4sGLZXvuryyJC7bj4xVPbfdn+5OGUZUKOObi7I4VifvOkQqERskhtzWWyGO1VpoMMOIzBM7xQuzjAEjdBgf3shtNjp48iBat1CufHwx+n+p1+GSBxiLVNltW4LJrU0kEi2twxs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
